import { Router } from 'express';
import { protect } from '../../middleware/auth.middleware.js';
import { requireRole } from '../../middleware/role.middleware.js';
import { validate } from '../../middleware/validate.middleware.js';
import { myWithdrawals, requestWithdrawal } from './withdrawal.controller.js';
import { createWithdrawalSchema } from './withdrawal.validation.js';
const router = Router();
router.use(protect);
router.post('/', requireRole('freelancer'), validate(createWithdrawalSchema), requestWithdrawal);
router.get('/', myWithdrawals);
export default router;
